### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by pbuzdin** [NaturalIntelligence/imglab#1]
![image](https://user-images.githubusercontent.com/1329807/36109138-9c946554-102f-11e8-964d-8223cdb662fb.png)

**Comment by amitguptagwl** [comment]
What is the issue @pbuzdin ?

**Comment by pbuzdin** [comment]
Disturbing modal on the page

вт, 13 февр. 2018 г., 6:32 Amit Gupta <notifications@github.com>:

**Comment by amitguptagwl** [comment]
Is it appearing only once (as expected) or repeatedly? or not being closed when you click on close button?

**Comment by pbuzdin** [comment]
why it exists?

**Comment by amitguptagwl** [comment]
Why shouldn't it be? It doesn't force you to do any action and appears only once. If you feel that this repository can't help you much, you are anyhow not gonna access that page again.
