### ISSUE TITLE
Bug: Mouse coordinates are wrong when zoomed in/out

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#104]
**About**
One of the contributors has discovered a bug in PR #95 which was raised to fix the issue #52. When a user zoom in/out the image, the function to get mouse coordinates return wrong value. Hence a feature point gets drawn on wrong position.

**To Reproduce**

1. Add a shape.
2. Add a point
3. Zoom In/out
4. Add a new point

**Screenshots**
![imglab-zoom-biug](https://user-images.githubusercontent.com/7692328/45603274-50c06d80-ba48-11e8-9ad3-25840b22ce40.gif)

**Console Errors**
No console error

**Device detail**
All

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
@Alvin-Voo in case if you wanna check.

**Comment by Alvin-Voo** [comment]
@amitguptagwl Alright let me look at it

**Comment by amitguptagwl** [comment]
Thanks

**Comment by alextychan** [comment]
I have found the cause of the bug and have fixed it in my local branch. Just waiting for my copy-paste functionality be approved before I push the fix.

**Comment by amitguptagwl** [comment]
@alextychan I hope you're taking care of it.

**Comment by amitguptagwl** [comment]
Oh. I even found that it is happening on all the zoom level.

**Comment by amitguptagwl** [comment]
1. if a shape is moved in same zoom level, then there is no issue.
2. if a shape is created on 100% zoom then we move it on 90%, 
it takes distance and shape relevant 90%. 
Now if we zoom back to 100% it doesn't change the size and location

**Comment by Alvin-Voo** [comment]
Yes, I see it too. zoom -> move shape -> zoom again, the shape will jump.
My guess is that something to do with wrong scaling, because after moving will have new positions. I am occupied with something now, but I could look at it maybe tomorrow or Saturday. Sorry guys.

**Comment by alextychan** [comment]
Solved and closed.
