### ISSUE TITLE
Custom category of a shape is not being saved

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#113]
**Describe the bug**
User is not able to set the custom category of a labeled shape.

**To Reproduce**
1. Create a shape on the image
2. Select the category from the already given categories
3. Create another shape
4. Select the previous shape
5. You can see previously selected category.
6. Now change to some category which is not in drop-down. The category will not be updated.

**Screenshots**
![labeling](https://user-images.githubusercontent.com/7692328/46200175-91649480-c32e-11e8-9947-5acec706ad57.gif)

**Console Errors**
No error on console

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by derekdkim** [comment]
I'm a beginner but would I be able to try my hand at this? I might be a bit slow but I think I can figure it out eventually.

**Comment by amitguptagwl** [comment]
@derekdkim This change is perfect for beginners. So please go ahead. But please update if you're not able to complete the issue.

You can check label-panel.tag.html, and store.js to find relevant functionality.

**Comment by derekdkim** [comment]
Awesome, I'll have a go at it!

**Comment by derekdkim** [comment]
I think I have a fix. Please review the PR when you have the time. If you make any changes, please let me know what you did so that I can learn from it.
