### ISSUE TITLE
Add default zoom level to settings

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#134]
> open http://imglab.ml/ > Open left top menu > Settings > General tab

We have to add an option in settings to set the default zoom level when an image loads. It should not impact current functionality. Settings should also saved in browser's cache.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
@ruyiweicas are you fixing this issue?

**Comment by ruyiweicas** [comment]
@amitguptagwl  no ....

**Comment by amitguptagwl** [comment]
Then you have posted your question on the wrong thread. Please be sure to comment on the right thread or raise a separate issue.
