### ISSUE TITLE
Importing in COCO format changes shape.type

### ISSUE THREAD

**Issue by alecGraves** [NaturalIntelligence/imglab#136]
**Describe the bug**
Stored type 'rect' shape objects are turned into type 'polygon' when imported from a .json with the coco.js dataformatter

**To Reproduce**

1. ```console.log(shape)``` in [the toCOCO loop in dataformatters/coco.js](https://github.com/NaturalIntelligence/imglab/blob/1876598a333045d053acb0d4e69af1f5f6717a7d/dataformaters/coco.js#L107)
2. ```console.log(labellingData[ image.file_name ].shapes[-1])``` in [the fromCOCO function in dataformatters/coco.js](https://github.com/NaturalIntelligence/imglab/blob/1876598a333045d053acb0d4e69af1f5f6717a7d/dataformaters/coco.js#L66)
3. Export then import some rectangle labels to/from a coco .json while watching console log

3. notice the change in shape.type from 'rect' to 'polygon'

**Device detail
 (please complete the following information):**
 - OS: windows
 - Browser firefox

**Additional context**
This did not impact saving and loading bbox data, which is the functionality I need. I have added this issue mostly to document the problem.

I think it may have something to do with [this logic](https://github.com/NaturalIntelligence/imglab/blob/1876598a333045d053acb0d4e69af1f5f6717a7d/dataformaters/coco.js#L46-L65) that tries to reconstruct different shapes.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
@jbovee will you be able to check the issue?

**Comment by amitguptagwl** [comment]
Thanks for your attention.

**Comment by amitguptagwl** [comment]
@jbovee I believe you wanted to check if the saved shape is rectangle then don't create polygon. What's about this condition;

```js
} else if (segLength !== 8 || (segmentation[2] - segmentation[0]) !== (segmentation[4] - segmentation[6]) || (segmentation[3] - segmentation[1]) !== (segmentation[5] - segmentation[7]) ) {
   //crete polygon
}
```

**Comment by amitguptagwl** [comment]
I've fixed this change. @alecGraves I hope you should not see the issue anymore. Feel free to reopen the issue if you still face it.
