### ISSUE TITLE
Console error in firefox browser: input is undefined

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#138]
**Describe the bug**
file open is not working in firefox but working in chrome.

**To Reproduce**
1. Go to http://imglab.ml/
2. Click on "open" in the left top menu bar.
3. Try to open previously saved data file
4. See an error in the console

**Console Errors**
```
TypeError: input is undefined[Learn More] openfile.js:23:1
readDataFile
http://imglab.ml/js/openfile.js:23:1
this.openFile tags/menu.tag.html.js:3:13 Fe/o<
http://imglab.ml/js/thirdparty/riot+compiler.min.js:2:12067
<anonymous> self-hosted:1085:17 
```

**Device detail
 (please complete the following information):**
 - OS: Ubuntu
 - Browser firefox

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by vardan10** [comment]
@amitguptagwl -- Seems a compatibility issue, has a simple fix. [Check this](https://developer.mozilla.org/en-US/docs/Web/API/Event/target#Compatibility_notes)

Will raise a PR for this.
