### ISSUE TITLE
Offline Installable Application

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#14]
Though Imglab works offline once it is loaded in the browser, it'll be more handy if it can be installed on the machine without internet.

Using node js, electron and other helpful technologies, it's installer can be created. Discussion and PR are welcome for this thread.

**Comment by Alvin-Voo** [comment]
Hi @amitguptagwl , may I recommend this awesome NW.js packager tool by jyapayne 
https://github.com/jyapayne/Web2Executable
he also maintains a packager tool for Electron.js
https://github.com/jyapayne/Electrify

Web2Exe is very simple to use, it lets you specify almost all configurations you could think of for an app. This includes icons, windows settings (size) etc. It also exports to all major platforms:
![screenshot from 2018-08-16 14-56-03](https://user-images.githubusercontent.com/28261161/44193549-d8733d80-a165-11e8-8c51-f3643b0e52d8.png)
![screenshot from 2018-08-16 14-51-17](https://user-images.githubusercontent.com/28261161/44193551-da3d0100-a165-11e8-9e5c-0c6831b03f79.png)

I had tried it on imgLab and below you can see I am playing with the offline app:
![imglab_ 14](https://user-images.githubusercontent.com/28261161/44193726-62bba180-a166-11e8-8e78-677c822b38b8.gif)

As with all packaged js apps, there's no need to install anything, just need to release/ship as a package like shown below. User can double click on the .desktop or .exe (or equivalent)

![screenshot from 2018-08-16 15-01-58](https://user-images.githubusercontent.com/28261161/44193607-0e182680-a166-11e8-9e1d-975f34818885.png)

I hope this helps ;)

**Comment by amitguptagwl** [comment]
@Alvin-Voo the gif master!! Yes it looks really helpful. I'll play with this next week (hopefully). BTW how do you make all these GIFs?

**Comment by Alvin-Voo** [comment]
@amitguptagwl I use peek
https://github.com/phw/peek
OSS rocks! ;)

**Comment by amitguptagwl** [comment]
Wow nice. I hope it'll work on my machine. will try after the vacation. Thanks

**Comment by amitguptagwl** [comment]
@Alvin-Voo I tried Electrify which didn't work. I believe because it is not node.js project. But Web2Executable worked perfectly.
