### ISSUE TITLE
how to export attribute info?

### ISSUE THREAD

**Issue by ruyiweicas** [NaturalIntelligence/imglab#141]
Tell us what feature you're looking for and how it can help you and others in general.

**Comment by amitguptagwl** [comment]
Can you please explain your question for better understanding? Imglab is the tool to annotate images and export data in the format supported by other object recognizers. Some of them may support to have attributes. You can't extract the attribute only information.

**Comment by ruyiweicas** [comment]
I see that imglab can label attribute information, but when I use mini or other data formats, I cannot export the attribute information I have labeled, such as gender, age, etc. What I want to ask is, how can I export the attribute information I have labeled?thank you @amitguptagwl

**Comment by amitguptagwl** [comment]
Please reopen this issue, if you still have the question.

**Comment by Partha2k** [comment]
What if I want attributes data in PASCAL VOC format? Can those attributes data be pushed into that?

**Comment by amitguptagwl** [comment]
it should be if supported by the format specified. Can you please share the expected and actual exported VOC file?

**Comment by beckstev** [comment]
Hi @amitguptagwl, 

I am currently trying to save the `attribute` feature of imglab to a `.json` file or find a way to convert `.nimn` to `.json`. Do you have any suggestions?  

__Please see my example:__

Here I wanna label the speed limit sig, which limits the max speed to 50 a.u.. As you can see, I created an attribute called `limit` with the value 50. 

![imglab](https://user-images.githubusercontent.com/22479623/60123356-8d638700-9787-11e9-866d-a4f75bc823f3.png)
__What did I do so far__: 

I saved the `.nimn` file and tried to open it with  _vim_. The file does include the following lines: 

`
»geschwindigkeitsbegrenzung.jpg¼¶geschwindigkeitsbegrenzung.jpg²²¶1280³851´»¶SvgjsRect1028³speed_limit³speed_limit³rect»909³289³90³72¹¶90³72¸¸954³325³909³90³289³72´»¶limit¸´¹²²´¹´¹
`
How can we convert it to `.json`? I already have tried to use this [online converter](http://nimn.in/nimnjs/).


__My system__:
- OS: Ubuntu 18.04 
- Browser: chrome

**Comment by amitguptagwl** [comment]
As I remember, imglab lets you save the project file in json/nimn both formats. However, in case if you don't find then open browser console and export the value of `labellingData` variable.
