### ISSUE TITLE
Can'T load project

### ISSUE THREAD

**Issue by jacquesj1** [NaturalIntelligence/imglab#145]
**Describe the bug**
Hello I started with the tool on windows10 and save my project with the nimn file format.
But when I want to load the project (open the nimn file) nothing appears 

**To Reproduce**
1/run cmd tool on windows10
2/ run live-server in the cmd tools
3/ click on the "menu" button and then "open"
4/ select the *.nimn file

**Device detail
 (please complete the following information):**
 - OS: windows10
 - Browser [ chrome, firefox]

**Comment by amitguptagwl** [comment]
the project file contains the detail of labeled images without image data. You'll have to import the images first and then open the project file.

**Comment by amitguptagwl** [comment]
@jacquesj1 I hope your problem must have been solved. Please reopen the issue or create new if you face any problem.

**Comment by jacquesj1** [comment]
Yes It solves the problem.
Best regards

Le sam. 19 janv. 2019 à 11:55, Amit Gupta <notifications@github.com> a
écrit :
