### ISSUE TITLE
Can I get numpy array of uploaded image or read it in cv2 ? 

### ISSUE THREAD

**Issue by MElHussieni** [NaturalIntelligence/imglab#147]
> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
If I can understand your question correctly you're looking for the option to export labeled data which can be read by cv2? if not can you please explain it.

Just to inform that, none of the exported data files contains image data including the project file.

**Comment by MElHussieni** [comment]
I know that exported data files contain image data, but I need the image to read it in cv2 and then pass for classifier in Keras. 
So I do not need the exported label in case of classification, otherwise I can use XML or JSON

**Comment by amitguptagwl** [comment]
> I know that exported data files contain image data

No! we don't export image data in data files.

> but I need the image to read it in cv2 and then pass for classifier in Keras.

You'll have to read the image file directly from the filesystem.
