### ISSUE TITLE
我想在项目的基础上做二次开发，但是没有看懂代码

### ISSUE THREAD

**Issue by wentieniu** [NaturalIntelligence/imglab#149]
我想在项目的基础上做二次开发，但是我没有看懂代码，前辈能跟我简单介绍一下，项目是用什么语言，和技术开发的吗？

**Comment by amitguptagwl** [comment]
编程语言：node.js
如果您正在寻找贡献，可以加入以下论坛。

https://github.com/socialat/team
https://discord.gg/Rp8FQ7Z
