### ISSUE TITLE
New UI Design

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#15]
With the inspiration of many photo editing software and to support other features in future, I was wondering if we should change the UI of `Imglab`.

Some points in my mind

1. Dark theme: Pleasant for eyes. More focus on currently open image.
2. cursor position on image or the position of feature point and label box should be displayed in bottom bar.
3. label name can be attached to label box
4. Left tool bar for selection, draw point, draw label etc.
5. Top toolbar action on currently selected tool or item on the image: delete
6. Optional mouse tracking lines, grid etc.
7.  Sliding "Time Saver" window. (Lets rename it to something else

**Comment by gsweetwood** [comment]
I think changing the opacity of the coordinate lines would look nicer.  Also, when a point is created, the little rectangle is created from the top left corner.  I think it would feel much better if it appeared in the center of the rectangle.

**Comment by amitguptagwl** [comment]
@gsweetwood I agree with your both points. 

This is the UI design We're aiming for. I'll update the design with all the suggestions.

![Final UI](https://github.com/NaturalIntelligence/imglab/raw/master/img/imglab_vision.png)

**Comment by amitguptagwl** [comment]
This is what I've done today. I'll be working on creating rectangle on canvas tomorrow.

![screenshot from 2018-05-24 21-29-08](https://user-images.githubusercontent.com/7692328/40497424-c25c0850-5f99-11e8-9852-4ca2a42001a0.png)

I'm not planning to move action bar on top. It looks weird. Top bar can be treated as menu bat or title bar.

**Comment by amitguptagwl** [comment]
It's quite difficult to decide which approach should be used for drawing: `div`, `svg`, or `canvas`. 

I've an idea how to draw polygon, and lines with `div`. But it can become complex with curves. Moreover implementing own solution is like reinventing the wheels. It's better to use some drawing library.

**Comment by rohitkrishna094** [comment]
I just wanted to confirm. Is version 2 going to be the main focus for future? If so, what happens to version 1? Thanks

**Comment by amitguptagwl** [comment]
Yes you're right. We'll migrate version 1 to version 2. Currently version 2 can handle all the tasks of version 1 except few UI things. Moreover we want to use nimn. Then we'll remove version 1.

**Comment by amitguptagwl** [comment]
This issue will be marked completed once the labeling window is designed.

**Comment by amitguptagwl** [comment]
Most of the UI targeted has been achieved. Hence closing this discussion. Some issues are still there and will be fixed.
