### ISSUE TITLE
Attributes data are not being exported in any chosen output format.

### ISSUE THREAD

**Issue by Partha2k** [NaturalIntelligence/imglab#154]
Adding attributes such as Gender and age shown below image is not reflected in the output label file for all formats. (PASCAL VOC, COCO, Dlib XML, DLib pts)

![Screenshot from 2019-05-17 16-06-16](https://user-images.githubusercontent.com/25670426/57922902-76936000-78be-11e9-9989-e0227ea88afb.png)

![Screenshot from 2019-05-17 16-12-57](https://user-images.githubusercontent.com/25670426/57922967-acd0df80-78be-11e9-8b50-79f1423ad716.png)

**Screenshots**

**Console Errors**

**Device detail
 (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Browser [e.g. chrome, firefox]

**Additional context**

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
Please refer the issue https://github.com/NaturalIntelligence/imglab/issues/141

Feel free to comment or reopen the issue, if your doubt is not clear.
