### ISSUE TITLE
Polygone tool

### ISSUE THREAD

**Issue by AlexGagne10** [NaturalIntelligence/imglab#161]
Hi, first of all, thank you for your amazing work. 
I have a difficulty with polygon tool. It's impossible to close my shape. Do you have any solution ?
Thank alot in advance

**Comment by amitguptagwl** [comment]
how are you closing the polygon? Please use the Enter key. It is completely working fine for me. Open the PR if you still face the problem.

**Comment by AlexGagne10** [comment]
I'm so sorry. Thank you very much.
