### ISSUE TITLE
Which library are you using to generate contributors image on README.md?

### ISSUE THREAD

**Issue by rohitkrishna094** [NaturalIntelligence/imglab#164]
This is just a question based issue. Sorry if this is the wrong place to ask it.

For this repo in the [README.md](https://github.com/NaturalIntelligence/imglab), towards the bottom, there is a section titled `Contributors`. Is that being auto generated? If so, how?

I mean this part.

![Untitled](https://user-images.githubusercontent.com/18495886/63219556-01942880-c142-11e9-9105-87b5349c52a0.png)

Thanks

**Comment by amitguptagwl** [comment]
well there is nothing wrong if you ask here. However, there is opensource.stackexchange.com which can help you in such questions better.

Now to answer your question, you need a server which can call Github APIs and render a svg that can be placed on your README.

**Comment by rohitkrishna094** [comment]
Thanks a lot. This was the first repo that I contributed to as part of open source. I am starting a practice project and remembered that this repo had that feature. Anyway thanks for accepting my first PR last year. Have a great day
