### ISSUE TITLE
Import Data in pts format

### ISSUE THREAD

**Issue by gunnarsundberg** [NaturalIntelligence/imglab#169]
The ability to import data in pts format would be extremely useful for annotating images across multiple sessions and adding annotations to existing sets. My research group would greatly appreciate this :-)

**Comment by amitguptagwl** [comment]
Import for pts format or any other format should not be difficult task. Unfortunately, I'm running busy with my current commitments. So it xan be delayed. I would appreciate, if you can create a PR for the same.

I didnt understand cache part in your statement.

**Comment by Staars** [comment]
I began with some work on this, but I am still not sure about the ideal user interface.
While testing with the ibug_300W...-dataset, I added some functions to the image-slider-file to auto-import the pts-file for the image-file with the same name, when a directory is imported.

This seems to work, but I have some questions:

- How important are the naming conventions inside "imglab" for the whole .shapes[]-stuff?
I used the image-name for the id and so on.

- How important is the correct bounding box?
I calculated a new one, based on minimal and maximal values for the feature points. This looks quite okay.

- How do I map the feature points to the mirrored images?
I did not implement anything yet. Is this simple x-mirroring, so if point 0 is i.e. on the left side in the original, will he move to right side . Or is it best practice to ignore the mirrored images completely and would it be better not to load them into "imglab" at all?

**Comment by amitguptagwl** [comment]
> How do I map the feature points to the mirrored images?

How is this related to imglab?

> How important is the correct bounding box?

Accuracy is must

> How important are the naming conventions inside "imglab" for the whole .shapes[]-stuff?

In general, image-name can be used as id. please check implemented code to get this answer.
