### ISSUE TITLE
Create Toolbar

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#17]
A user can create a label box or feature points inside the label box. For this he/she needs to click on a switch;

![switch](https://user-images.githubusercontent.com/7692328/39279504-30b6ff88-4917-11e8-8aaa-daf6628f7f58.png)

Instead, we want to provide a toolbox , preferably left hand side, like other image editing tools where user can select the tool icon. It'll give the benefit of creating multiple tools.

**Comment by malfple** [comment]
Hi! Can I take this one?

**Comment by amitguptagwl** [comment]
You're welcome @malfple . Please also read [contribution guideline](https://github.com/NaturalIntelligence/imglab/blob/master/.github/First_Time_Contributors.md)

**Comment by amitguptagwl** [comment]
![Final UI](https://github.com/NaturalIntelligence/imglab/raw/master/img/imglab_vision.png)

**Comment by amitguptagwl** [comment]
covered in UI renovation
