### ISSUE TITLE
Keypoint dataset creation

### ISSUE THREAD

**Issue by dvkeulen** [NaturalIntelligence/imglab#176]
I am currently trying to create a COCO style keypoint dataset for pose estimation. For this I am using the _point_ tool but the right column panel doesn't seem to recognise the annotation; I can't add a category. Is this normal behaviour or am I using the program wrongly?

kr,

David

**Comment by amitguptagwl** [comment]
Probably I didn't understand your concern. But a point-tool is to mark feature-point inside a label shape. So if you select the feature-point that you created, the right-side panel shows you the information of its parent label shape.
