### ISSUE TITLE
Create Action Bar

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#18]
After creating a label or feature point on an image, user can delete selected element from the left side widget.

![widget](https://user-images.githubusercontent.com/7692328/39279607-bfe91b78-4917-11e8-8d3b-2e9456ac51c0.png)

Instead, we would like to create an action bar between canvas and thumbnail slider with "delete", "empty", "move" buttons. Appropriate options should be visible or enable. Eg when a feature point is selected then "empty" option either should not be visible or disabled.

**Comment by gsweetwood** [comment]
@amitguptagwl Hi, I think I will take a stab at this issue if it's still available.  I have a question though.  What is the purpose of the "move" button?  I don't see it in the current version.

**Comment by gsweetwood** [comment]
I moved the "delete" and "empty" buttons to above the image.  I also added an animation to hide the "empty" button when the 'Points' is selected and reappear when 'Box' is selected.  Is this what you are looking for?
![points selected](https://user-images.githubusercontent.com/25124281/40274368-d4ec926e-5b89-11e8-9d0b-ca11dfc2f62b.JPG)
![box selected](https://user-images.githubusercontent.com/25124281/40274370-df581f02-5b89-11e8-99b2-b6cd233738b8.JPG)

**Comment by amitguptagwl** [comment]
Sorry for the late response. I was busy to design the final UI I'm aiming; Please check [vision](https://github.com/NaturalIntelligence/imglab/blob/master/vision.md) page.

![Final UI](https://github.com/NaturalIntelligence/imglab/raw/master/img/imglab_vision.png)

This is how the final UI should look.

As a part of this story we need to create the **action bar** with delete and empty icons. Icons should be displayed only when relevant label is selected.

**Comment by amitguptagwl** [comment]
refer v2.html
