### ISSUE TITLE
Create Polygon

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#19]
Through imglab, you can only make the rectangular labels. As a part of this issue, we want to let user create polygons. 

> This issue has dependency on issue #17 Create Toolbar

Features
* The points of the polygons should be draggable to increase accuracy.
* Selected polygon can be deleted

**Comment by UmangGPatel** [comment]
hi, there it seems that I can start my contribution to open source with this project.
How can I start?

**Comment by aamarill** [comment]
Hello :)

I am looking to make my first open source contribution.
I have good HTML, CSS and JS skills. Can I claim this issue?

Thanks in advance!

**Comment by UmangGPatel** [comment]
bro I have already claimed the issues please try another one

**Comment by aamarill** [comment]
@UmangGPatel  my apologies, I didn't see your previous message. Best of luck 😄

**Comment by UmangGPatel** [comment]
@amitguptagwl I have some doubts so please solve this.
can we make the option that first plots the point by the user and then creates a polygon of that points or we provide an option such as shape making tool in word or other software in which shape have same internal angles as predefined?

**Comment by amitguptagwl** [comment]
@UmangGPatel If you attempt to do it using HTML5 canvas then you may have to change the existing functionality to create labels (rectangle) and feature points. Which may increase the complexity. So if you feel you can handle all using the HTML5 canvas it is fine.

**Comment by amitguptagwl** [comment]
@aamarill Please have a look [here](https://github.com/NaturalIntelligence/imglab/issues)

**Comment by amitguptagwl** [comment]
@UmangGPatel any update on the same. Feel free to ask questions to clear any doubt.

**Comment by UmangGPatel** [comment]
I have analysed your code and  I understand  that you are not using canvas and  
SVG to draw a rectangle and points.so I have tried your method of plotting point but I have still no idea about how you are drawing a box so guide me @amitguptagwl

**Comment by amitguptagwl** [comment]
The Box is nothing but a `div` with border. I create it on `mousedown` and keep changing it's height and width on `mousemove` till `mouseup`.

If you feel that canvas is a good option. Go for that. We may use some libraries for drawing rectangle, point, and polygon. But please keep in mind that all the features should work, like selection of box, moving it on canvas, mouse and key events etc.

**Comment by amitguptagwl** [comment]
![Final UI](https://github.com/NaturalIntelligence/imglab/raw/master/img/imglab_vision.png)

**Comment by amitguptagwl** [comment]
This feature has been covered in new UI renovation.
