### ISSUE TITLE
On using imglab

### ISSUE THREAD

**Issue by NIDHIPANDA** [NaturalIntelligence/imglab#2]
Hii,
I want to detect face from HOG based face detector using dlib's face detector and then train this for land mark detection using my dataset. Can I load this face points and generate one .xml file using this imglab tool. If yes how to do it. Is there any specific format to load the face points (i.e. 4 points of rectangle)
Please help me in this regard.

Regards
Nidhi

**Comment by amitguptagwl** [comment]
I created this tool few months back so I exactly didn't remember if there is some feature displayed on webpage was left to implement.

Open the [imglab](https://naturalintelligence.github.io/imglab/) online. You'll find 'Browse' button right side to load the file. imglab don't restrict you to load file with specific number of landmarks.

I hope you must have already watched [video tutorial](https://www.youtube.com/watch?v=4yLL21weN8w)

if you find that this doesn't solve your problem. please share the sample file and what exactly you are looking for.

**Comment by NIDHIPANDA** [comment]
Thank you Amit for your reply. I have watched your youtube video. It is shown there that we can browse landmark or face position. What I didn't understand it how to load points and use it. I tried to load images and corresponding face detected points using one xml file. But some how it didn't work. Do you have any written document on it. M not able to know what m missing.  As I said earlier **I want to detect face from HOG based face detector using dlib's face detector and then train this for land mark detection using my dataset.**

**Comment by NIDHIPANDA** [comment]
The part of browsing an image and creating a rectangle on it and saving the point in dlib formate is working fine. But some problem is with loading face points.

**Comment by amitguptagwl** [comment]
Hmm.. let me check

**Comment by NIDHIPANDA** [comment]
Thank you for your response. I will wait for the updates.

**Comment by amitguptagwl** [comment]
I'm done with basic refactoring. And you can restore face points from json now. I'm still working on loading face points from XML. It needs some changes in [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser)... so keep watching

**Comment by amitguptagwl** [comment]
I've done with rest of the changes. You can give a try now. I'll keep the card open for next few days. Please let me know if you face the issue.

Any new feature or enhancement may be delayed ;) but you can raise an issue always.

**Comment by NIDHIPANDA** [comment]
Thank you so much. Now its working.

**Comment by NIDHIPANDA** [comment]
I am facing a problem in using Face++ . I created a free account in face++ and got one api_key and api_secret. It is showing "**Error in connecting face++ API. Check console for more deetail"**. **What does it mean?**  There is one console option in face++. For my account console is as the image I have attached. 
![screenshot from 2018-04-16 18-07-46](https://user-images.githubusercontent.com/23721905/38794554-22899ff2-4173-11e8-85c9-22b3a6a63dd9.png)

**Comment by amitguptagwl** [comment]
@NIDHIPANDA It looks like, there is no issue with Face++ API. I'm fixing the integration part. The issue that you are facing is completely related to face++. Please drop an email to them. Most of the newly registered users faces issue.
