### ISSUE TITLE
Cursor X Position Displays Extra Numbers

### ISSUE THREAD

**Issue by gsweetwood** [NaturalIntelligence/imglab#22]
The x position of the cursor displays extra numbers.  In the image below it's displaying ".84375"  Even if that number is technically correct (I don't know if it is or not), it should probably just display a whole number and not a decimal.  This was in Chrome.  A different number appeared in FireFox.  And I actually couldn't get any image to load in IE, but that should be a separate issue.

![x position issue](https://user-images.githubusercontent.com/25124281/40275667-866088cc-5bab-11e8-9880-774e5538c696.png)

**Comment by ToastCheng** [comment]
Does this happen all the time? 
I had a little test and the x value is always an integer(fixed already?).

**Comment by gsweetwood** [comment]
The issue still exists.  When I change the zoom on my browser, the number after the decimal changes.  Chances are that if I can see it, others might as well.  It's a really easy fix.

**Comment by amitguptagwl** [comment]
As I've already done the changes for [v2](https://naturalintelligence.github.io/imglab/v2.html). This issue will not be fixed, even if it is there.
