### ISSUE TITLE
Support PascalVoc XML format

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#24]
Currently imglab can export data in dlib pst or XML file only. We want to support **PascalVoc XML** as well.

labellingData format: https://github.com/NaturalIntelligence/imglab/blob/master/js/nimnObjStructure.js

Sample format: 
```xml
<?xml version="1.0"?>
<annotation>
	<folder>images</folder>
	<filename>raccoon-63.png</filename>
	<path>/Users/datitran/Desktop/raccoon/images/raccoon-63.png</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>600</width>
		<height>400</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>raccoon</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>74</xmin>
			<ymin>107</ymin>
			<xmax>280</xmax>
			<ymax>290</ymax>
		</bndbox>
	</object>
	<object>
		<name>raccoon</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>227</xmin>
			<ymin>93</ymin>
			<xmax>403</xmax>
			<ymax>298</ymax>
		</bndbox>
	</object>
</annotation>
```

Note: 

* Web version of imglab can't extract the value of folder name so it should be be set to UNKNOWN.
* segmented, truncated, difficult, and depth fields can be set to 0
* pose field can be set to 'Unspecified'
* Value for `object.bndbox` can be taken from `labellingData[n].shapes.bbox`

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by AnshuOnGit** [comment]
@amitguptagwl Could you please detail where we are exporting data, I mean UI flow

**Comment by amitguptagwl** [comment]
If you open [v2.html](https://naturalintelligence.github.io/imglab/v2.html), you can try the application to understand it better.

1. Upload some images in thumbnail slideer
2. click on thumbnail
3. draw some shapes on the image
4. save the data

You'll get 3 options. We want to introduce 4th option as a part of this issue.

**Comment by amitguptagwl** [comment]
@AnshuOnGit Are you able to manage this? Let me know if you're busy some other stuff or still willing to work on this issue.

**Comment by AnshuOnGit** [comment]
@amitguptagwl I am looking into it.

**Comment by amitguptagwl** [comment]
Thanks for update @AnshuOnGit . Please discuss here if you stuck in any issue

**Comment by amitguptagwl** [comment]
@AnshuOnGit I've updated the issue with both formats. Now it just a matter of a for loop. Let me know, in case you're not able to continue on this issue.

**Comment by AnshuOnGit** [comment]
@amitguptagwl could you please give time till this weekend?

**Comment by amitguptagwl** [comment]
no problem. Ask me the questions if you have related to the implementation

**Comment by amitguptagwl** [comment]
@AnshuOnGit As the issue is pending from a long time, I've implemented it. You can check `dataformats\pascal_voc.js` for implementation.

If you wanna give it a try, I've left the import part Pascal VOC -> labellingData

Some implementation help

```js
fromPascalVOC : function(){
        var inputData = parser.parse(data,{
            attributeNamePrefix : "",
        });

        if (!labellingData[inputData.filename] ){
            labellingData[inputData.filename] = {
                shapes : []
                //other properties
            }
        }
    },
``
