### ISSUE TITLE
Fix Icons (html, css)

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#27]
starting point: v2.html
link: https://naturalintelligence.github.io/imglab/v2.html

Following issues has to be fixed
1. Polygon icon need to be transparent. [done]
2. display bulb icon for Labels only tool button [done]
3. keyboard icon need to be aligned properly [done]
4. circle icon should not cut [done]
5. point icon should be smaller than circle and it should be filled circle, not the ring [done]
6. Zoom (magnifier) icon instead of 2 zoom in/out icons [done]
7. Imglab text should be aligned in middle with logo

**Comment by amitguptagwl** [comment]
point 3 is fixed

**Comment by amitguptagwl** [comment]
point 2, 6 are also fixed

**Comment by nimaosu** [comment]
Hello, I would like to attempt issues 4 and 5. Is this okay?

**Comment by amitguptagwl** [comment]
Yes please.

**Comment by scwong93** [comment]
May I tackle issue 7?

**Comment by amitguptagwl** [comment]
@scwong93 issues 2,3,6 are fixed. Issues 4,5 are being handled by @nimaosu . You can pick rest of the issues.

**Comment by nimaosu** [comment]
Hello, I'd like to apologize as some issues came up in my schedule and I am unable to address issues 4 and 5 at this moment. I'd like to open up the issues for people to pick up. Sorry again.

**Comment by Calstream** [comment]
Hello, I'd like to try issues 4 & 5.

**Comment by chrisperrins95** [comment]
Hello, I'd like to try issue 1.

**Comment by chrisperrins95** [comment]
@Calstream While trying to solve issue 1, i found out how to solve issue 4 and 5!
Download InkScape, open point.svg and re-centre the image.

**Comment by chrisperrins95** [comment]
Hi, I've fixed the issue. @Calstream  our issues are very similar if you want to know how to fix it let me know. 
@amitguptagwl  Once i have fixed the issue what do i do next? Sorry I am new

**Comment by amitguptagwl** [comment]
"Race 3" sorry I was late to respond. @chrisperrins95 You need to raise the PR. @Calstream yes please go on.
