### ISSUE TITLE
svg.js: a shape should not be draggable when the point tool is selected

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#30]
starting point: v2.html
link: https://naturalintelligence.github.io/imglab/v2.html

1. Load an image into the galleries
2. select an image to load in workarea
3. draw a rectangle on image
4. select point tool and create a point on rectangle . hold the mouse button and drag. shape should not be dragged

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by rohitkrishna094** [comment]
I would like to try this. When you say you don't want the shape to move, you are referring to rectangle right? Because when we try to add red points at a faster pace, we will drag our mouse unintentionally which actually also drags the green rectangle. So we should stop that from happening right?

**Comment by rohitkrishna094** [comment]
Ok, not I understand most of it. I will try with this issue and comment here again if I stumble upon any problems. Thanks

**Comment by amitguptagwl** [comment]
@rohitkrishna094 are you still on the issue?

**Comment by rohitkrishna094** [comment]
Sorry for the late reply. Yes I am this issue. Will complete is asap and do a PR for review.

**Comment by amitguptagwl** [comment]
Thanks Rohit.

**Comment by amitguptagwl** [comment]
@rohitkrishna094 As this issue was open from a long time, I've fixed that. Here is the solution for learning purpose;

```js
currentTool.on('mousedown', function (e) {
    if(!selectedTool || selectedTool.type !== "move"){
        e.preventDefault();
        e.stopPropagation();
    }
});
```

**Comment by rohitkrishna094** [comment]
Oh sorry. Totally forgot about this issue. Thank you, that was a great learning opportunity.
