### ISSUE TITLE
Show mouse tracking line (html, css, js)

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#31]
starting point: v2.html
link: https://naturalintelligence.github.io/imglab/v2.html

Just like [version 1](https://naturalintelligence.github.io/imglab/) we need to show vertical and horizontal crossing lines to track mouse pointer.

**Comment by rohitkrishna094** [comment]
Would like to work on this. Would be my first pull request. All I have to do is add stuff to workarea.tag html file right? Thanks

**Comment by amitguptagwl** [comment]
Yes. uiaction.js can give you snippet idea, if you want

**Comment by rohitkrishna094** [comment]
Hey for some reason I am getting a `riot` error. This did not happen yesterday. The version 2 doesn't work even after going to https://naturalintelligence.github.io/imglab/v2.html or even after trying it locally.

I get an error saying `Cannot read property 'src' of undefined` from `riot+compiler.min.js` file. Tried checking on chrome as well as firefox.

**Comment by amitguptagwl** [comment]
It's working fine for me. Can you please open the console and check what error is. And if you can share the screenshot.

**Comment by rohitkrishna094** [comment]
![Riot-Error](https://user-images.githubusercontent.com/18495886/41350749-bb2e36d0-6ed9-11e8-9b33-68e16df2ef7d.png)

Here is the screenshot. I am on Windows 10 and my browser is chrome. I tried checking it locally as well. The moment I load an image, I get that error. Locally the riot version that I tried in package.json is `^3.10.1`

**Comment by amitguptagwl** [comment]
I've checked it locally and there is no issue due to the PR at least, let me check on mac.

**Comment by rohitkrishna094** [comment]
This is interesting. For some reason, if I go back to commit `38eae298d3b3cf77fef4ae9f1a4df10e9a6cd7f4`, I do not see that error. But if I even go up even by one commit, I get that error back. I only have a Windows machine, so I am not sure if it's something to do with my Windows or not.

**Comment by amitguptagwl** [comment]
Sue the MS ;) 
well let me check on my windows then. I hardly open it once in an year.

**Comment by rohitkrishna094** [comment]
I actually checked the website in another pc that I have which runs ubuntu. I get the same error for version 2 as well. How are you supposed to load an image in v2? I just click the image icon at the bottom and add an image from my computer. In the previous commit, upon adding there was no `riot` error. But for the current version, irrespective of OS, I am getting the same error.

**Comment by amitguptagwl** [comment]
Sorry this is my bad. I tested the app without loading the image. There are many errors I can see on console. Let me check what are they.

**Comment by amitguptagwl** [comment]
@rohitkrishna094 thanks for reporting there were some issues with previous PR merged. I've fixed that now. You should not see any issue now.

**Comment by rohitkrishna094** [comment]
Nice, then I will get back to working on this issue. Thanks for your help.
