### ISSUE TITLE
Add key mapping for quick action (basic js, svg.js ) related to moving shape

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#34]
Demo: https://naturalintelligence.github.io/imglab/

**workarea.tag.html**
* Ctrl + arrow key: to move a selected shape(s) by 1 pix

Hint code:

```js
if(up) diffY = -1
if(down) diffY = 1
if(left) diffX = -1
if(right) diffX = 1

selectedShapes.forEach(shape => { 
   shape.move(shape.rbox.x + diffX ,shape.rbox.y + diffY) ;
}
```

*Note* - all the new key mappings need to be mentioned in `shortcuts.tag.html `

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by devamaz** [comment]
Will love to work on this

**Comment by amitguptagwl** [comment]
Please go on. I hope, it'll not take much time.

**Comment by devamaz** [comment]
Sorry man didn't check my feeds will work on it today

**Comment by devamaz** [comment]
Hy need some help with the selectedShapes they are the selectedElement right?

**Comment by amitguptagwl** [comment]
if you mean by variable name it should be `selectedElements`

**Comment by devamaz** [comment]
ok Thanks

**Comment by devamaz** [comment]
Sorry can't continue with this if another person can take

**Comment by amitguptagwl** [comment]
no problem

**Comment by amitguptagwl** [comment]
Snippet for reference

```js
selectedElements.forEach(el => {
    el.parent().dy(-1);
});
```
