### ISSUE TITLE
Bootstrap: adjust grid on small browser

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#36]
starting point: v2.html
link: https://naturalintelligence.github.io/imglab/v2.html

On top right side there are 3 buttons: plugins, keyboard, donate. When the browser window is < 1412px. They are not properly aligned. 

All the elements in a menu should be aligned for different screen size.

**Comment by JoelLau** [comment]
going to attempt to fix this!

**Comment by AnshuOnGit** [comment]
Hi @amitguptagwl  I would like to take this up

**Comment by amitguptagwl** [comment]
Sure, pleas go on. Just ensure that you test the application before raising
the PR and keep the console error free.

**Comment by AnshuOnGit** [comment]
@amitguptagwl  may i know the initial setup for making web app up on local laptop

**Comment by amitguptagwl** [comment]
`git clone` . It is made in html, css, and js. You can use any server to start it. or open the v2.html directly in browser. However if you already have node js installed on your machine, you can install http-server to make it easy.

**Comment by AnshuOnGit** [comment]
Please review https://github.com/NaturalIntelligence/imglab/pull/41

**Comment by amitguptagwl** [comment]
fixed
