### ISSUE TITLE
Save data to browser cache

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#37]
Currently all the data is being saved to `labellingData`. We want to keep labellingData sync with browser store securely. So if the browser is accidentally closed, user should not loose data.

Considerations
1. Anytime labellingData is updated, deleted, populated through 3rd party plugin both copies must be in sync .

**Comment by LandoLucas** [comment]
Hi, I'd like to contribute with this issue. Should I assign it to myself or just send a PR when I'm ready? 
Thanks

**Comment by amitguptagwl** [comment]
Sure go on. PR is sufficient. Just please take care that if you get engaged
with something else, plz inform here.

**Comment by LandoLucas** [comment]
Hi, is there any instructive on how to compile and run the application? Do you use a server or just open an html page on a browser?
I see that there is an index.html and a v2.html that both could be an entry point of the application.
Thanks

**Comment by amitguptagwl** [comment]
> is there any instructive on how to compile and run the application? Do you use a server or just open an html page on a browser?

Application need not to be compiled. Opening with browser may work in some cases but it's better to start with some [http server](https://www.npmjs.com/package/http-server)

>I see that there is an index.html and a v2.html that both could be an entry point of the application.

`labellingData` is available only for v2.html. So that'll be starting point for this issue.
