### ISSUE TITLE
Save feature points which are generated via. face++ API

### ISSUE THREAD

**Issue by NIDHIPANDA** [NaturalIntelligence/imglab#4]
Can I save the face and landmark point which I am getting by using face++ API. I tried to save it but the generated .xml file in not including any points.

**Comment by amitguptagwl** [comment]
Please remember that when you fetch some data from face++, it has more detail than only face location and landmark points. When you export it into dlib xml or pts format, you lose that detail. So save json file as well. You can check json file manually to know what extra detail it has.

**Comment by amitguptagwl** [comment]
fixed
