### ISSUE TITLE
Firefox UI : Bootstrap : Extra space above the row

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#42]
[v2.html](https://naturalintelligence.github.io/imglab/v2.html) looks fine on chrome but on firefox it moves the menu bar down.

![screenshot from 2018-06-19 11-54-51](https://user-images.githubusercontent.com/7692328/41580236-c479cb2c-73b7-11e8-8284-aa470d6bfe50.png)

Hint: Try line height of the container.

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by zlateff** [comment]
This looks like a perfect opportunity for first-time contribution. Can I give it a shot?
