### ISSUE TITLE
Javascript : Warn user for unsaved data on closing window

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#47]
If user has not saved the data and close the window, he should be warned before closing the window.

Starting point: v2.html

Don't show when

* Use has started an application but not uploaded any image yet
* User has uploaded images but there is no labeling data present

ref: https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by reploid-Zero** [comment]
Hello, i'm interested in solving this issue. Please assign me :)

**Comment by amitguptagwl** [comment]
Currently we 're saving data in browser cache. So I believe we don't need this card anymore. Thanks to show your interest. And sorry to close this issue. But you can check other issues.

> [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) this project for further updates 
> You can also join [team](https://github.com/socialat/team) to support opensource community
