### ISSUE TITLE
SVG fill color is not working

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#48]
URL : https://naturalintelligence.github.io/imglab/v2.html
starting point : v2.html

Issue:

1. open above link
2. upload some images in thumbnail slider
3. click on an image
4. draw a shape from left toolbar
5. Click on lightbulb tool (left bottom)
6. In the action bar, you can see the slider (tags/actions/lightbulb-action.tag.html)
7. When we change the value of slider, it changes the `fill-opacity` of SVG. But it is not working.

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by ShreyashAnarase** [comment]
Hi. This is my first time. Can I try?

**Comment by amitguptagwl** [comment]
Yes please.

> [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) this project for further updates 
> You can also join [team](https://github.com/socialat/team) to support opensource community

**Comment by ShreyashAnarase** [comment]
How do I do it? I'm not sure can you help/guide?

**Comment by amitguptagwl** [comment]
@ShreyashAnarase I hope you're able to get what to do and how to do.
