### ISSUE TITLE
Bug: Extra padding in left

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#50]
Starting point: https://naturalintelligence.github.io/imglab/v2.html

Issue: Tools displayed in left bottom are extra padded

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by lucasvienna** [comment]
Hello! Tried to tackle this one, but having some trouble getting it to run properly on my local machine. For some reason, the entire left sidebar is not showing up when I try to open `v2.html`. Cloned locally, ran `npm i --save` and opened the page on Chrome. Anything I'm missing?

**Comment by amitguptagwl** [comment]
You need not to setup node project. Install `npm -g i http-server`. Then just run `http-server` command from project root folder. Now open the localhost in browser, you must see everything on the place.

> [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) this project for further updates 
> You can also join [team](https://github.com/socialat/team) to support opensource community

**Comment by lucasvienna** [comment]
It seems that removing `align-items-end` from your toolbar div fixes the issue. So far haven' found anything broken by that. Following your tech doc for testing

**Comment by amitguptagwl** [comment]
Hmm, if we remove that it will shift the 2nd tool plate up. Though we can do that, I was wondering if we can fix it without that.

**Comment by lucasvienna** [comment]
I guess it depends on which browser you're running it then. On Chrome 67 and Safari, the items stay on the bottom.
