### ISSUE TITLE
svg.js : copy paste svg elements

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#53]
Starting point: https://naturalintelligence.github.io/imglab/v2.html

While annotating the images sometimes you may need to copy almost similar element on the same image or across the images. It'll be more handy when we can just copy paste svg elements (workarea.tag.html). So that the user's effort and time can be saved.

Check [technical documentation](https://github.com/NaturalIntelligence/imglab/blob/master/docs/technical.md).

**Comment by amitguptagwl** [comment]
Steps
check commented code in `workarea.tag.html`

```js
} else if (e.key === 'c' && e.ctrlKey) {
    copiedElements = [];
    //loop through selectedElements and copy all the shapes in copiedElements
    e.preventDefault();
    e.stopPropagation();
}else if (e.key === 'v' && e.ctrlKey) {
    //loop through copiedElements and push new shapes in currently selected image
    //use the new IDs : shapetype + shapeIndex, shapetype + shapeIndex + point + pointIndex
    e.preventDefault();
    e.stopPropagation();
}
```

**Comment by alextychan** [comment]
Hi, I would like to take up this issue. 

My understanding is that if a polygon is selected, then all its children/points in it should also be copied. If the selected items are points, then I only copy the points. But what if a user selects a mixture of both polygons and points?

e.g. user selects polygon#1001 and 3 points in polygon#1002. Should I limit it such that only polygon#1001 and all its children are copied or should everything be copied?

**Comment by amitguptagwl** [comment]
Sure @alextychan . Let me know if you need guidance.
