### ISSUE TITLE
Does the landmark order matter?

### ISSUE THREAD

**Issue by off99555** [NaturalIntelligence/imglab#55]
In dlib face, there are 68 points. Is it necessary that you have to order them right?
For example, you might label your eyebrow first before your cheek if order doesn't matter.
And what if the landmark labeler mislabeled the number of points to, say 67 or 69?

**Comment by amitguptagwl** [comment]
This question is related to dlib not this project. However , in my
knowledge, yes you need to. But I'm not currently maintaining the order in
v2 when transforming from face++ output.

I'll cross check that.

**Comment by off99555** [comment]
OK. So we must clearly tell labor that they need to label exactly in the order we choose, right?

**Comment by amitguptagwl** [comment]
dlib don't restrict you for 68 points, you can have any number of points you want. But you'll have to do necessary settings while generating the models from face labeled data. So as you said, you want to label only the mouth, yes you can do that.

v2 is under development but being delayed due to the work on other projects. In v2, I can make it easy that even if you don't draw points in order you can always generate the file with ordered points.

I'll have to double check about order. Can you please ask on dlib community as well?

**Comment by off99555** [comment]
I asked the question here:
https://github.com/davisking/dlib/issues/1384

For v2, are you going to do some type of X,Y sorting? I don't think that'll work if the face is rotated then you mess up the order of the face.

**Comment by amitguptagwl** [comment]
Of course not. I'll give the people easy selection of points labels from drop down. In case of converting from fpp result, I already have label information. So I just need to map.

**Comment by off99555** [comment]
The `dlib` creator said that order is irrelevant.

**Comment by amitguptagwl** [comment]
It's a good news for you. As I remember, they're irrelevant when generating the model but the model marks the landmark points always in an order so you can perform expression detection.

**Comment by off99555** [comment]
Well, I misunderstood what he said. He meant that we don't have to put landmark 1 close to landmark 2. That's what he meant by order. So, in the end, the order is relevant. It needs to be the same for all images.

**Comment by amitguptagwl** [comment]
Hmm... better to leave this card open until we implement it.

**Comment by amitguptagwl** [comment]
@off99555 While I was working to solve this issue I just realized that dlib does not restrict to 68 points and their position. It returns you the position of points in the same order they were created in training data.

Eg

You created a training data with 4 points: left eye, right eye, nose tip, and chin. And you labelled these points : 1,2,3,4 respectively. Then you should maintain this order in all the images in training data.

So 
1. if you are fetching data from Face++ API (83 points). I'll create them in the order dlib needs. But you'll have to remove extra points or add extra points depends on how many points you're targeting in dlib
2. If you're manually creating points you'll have to change their order in case if you don't create them in the same order always.

I'll create some easy interface to speed up your work.

**Comment by amitguptagwl** [comment]
In version 2. All the landmark / feature points can be ordered manually to maintain the order. I'll use their order (not their label) when exporting to dlib. Moreover, I'm also arranging fpp points in dlib parts order.
