### ISSUE TITLE
UX,UI : Key mapping with menu item

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#59]
https://naturalintelligence.github.io/imglab

User can see key mappings when he clicks on keyboard icon. In addition, it'll be good if we display key mappings with each menu item. 

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by DheenodaraRao** [comment]
Can you be more specific? I am interested to contribute.

**Comment by amitguptagwl** [comment]
If you'll visit mentioned link, you'll notice a 3 line icon on top left corner. When you'll hover on that you'll see list of menu items.

We want to show the key mapping with each item floating to the right.

Open - `Ctrl + i`
Save - `Ctrl + e`

**Comment by Alvin-Voo** [comment]
Hi @amitguptagwl , are you referring to the tooltip when mouse hover over the Open and Save?

I saw that you had jquery-ui installed. I did a small jsfiddle using jquery-ui:
![imglab_ 59](https://user-images.githubusercontent.com/28261161/44195487-ca282000-a16b-11e8-88f7-053b0cbe019c.gif)

Please tell me if this is what you are looking for. Thanks.

**Comment by amitguptagwl** [comment]
Yes that can be a way. However I was aiming to show them all the time in the right side of each menu item. So the user can press relevant key instead of hovering the mouse to know.

**Comment by Alvin-Voo** [comment]
@amitguptagwl Like this?

![screenshot from 2018-08-17 11-52-48](https://user-images.githubusercontent.com/28261161/44247046-4118f380-a214-11e8-82d5-9386e8876935.png)

**Comment by amitguptagwl** [comment]
Yes but without background color.

**Comment by Alvin-Voo** [comment]
@amitguptagwl How bout this. The simpler the better?

![imglab_ 59](https://user-images.githubusercontent.com/28261161/44440565-34711280-a5fb-11e8-80ca-bd4fd29ee80f.gif)

**Comment by amitguptagwl** [comment]
This is good.

**Comment by Alvin-Voo** [comment]
@amitguptagwl  PR created. Thanks!

**Comment by amitguptagwl** [comment]
Thanks @Alvin-Voo . merged
