### ISSUE TITLE
UI: Bootstrap switch

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#6]
There is a switch just below the image gallery slider and just above the canvas / work area. It is helpful to switch between creating label or point. It doesn't display correctly in all the browsers. 

I believe setting max-width may fix the issue. Manual switch or other libraries can also be the solution

![screenshot from 2018-04-26 05-56-05](https://user-images.githubusercontent.com/7692328/39279504-30b6ff88-4917-11e8-8aaa-daf6628f7f58.png)

**Comment by al1khavari** [comment]
Hi , i take this task, can you tell me in which browser does this happen?

**Comment by amitguptagwl** [comment]
It's weird that when I open [online tool](https://naturalintelligence.github.io/imglab/) in chrome I can see the issue. But if I run it locally on the same browser then I don't see the issue.

**Comment by amitguptagwl** [comment]
@al1khavari ! in case if you've not started with the implementation of this issue, I would like to close this issue as out of scope due to the issue #17 . I hope your effort is not wasted.
