### ISSUE TITLE
When a feature point is selected in label panel then corresponding SVG element should be selected

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#63]
The code is already there to identify the SVG element and select it. `workarea.tag.html`

![imglab](https://user-images.githubusercontent.com/7692328/44836803-8c3ff700-ac55-11e8-9856-b8ad57e9e4e2.gif)

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by urielintemperie** [comment]
Hi. I can help with this. Could you assign it to me?
