### ISSUE TITLE
Change size of landmark point (SVG circle )

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#65]
Landmark points are small and hard to find on an image. Hence we've introduced that for some images they are bigger and for some images they're not much visible due the back ground.

Hence we're planning to create an action bar which can let the users to change it's size.

To do it,
1. You can copy paste `tags\actions\lightbulb-action.tag.html`
2. set the css property on change event

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by jaknowles97** [comment]
Hey I'm new to contributing and have been attempting to add this feature. I used the lightbulb-action.tag.html as boilerplate but when I tried to add the css to the .labelpoint class, it gets completely ignored. I confirmed with dev tools that the css was being added/changed but it was being overwritten. I noticed a "r" attribute. Changing the value sucessfuly changes the landmark point size.

**Comment by jaknowles97** [comment]
![example](https://user-images.githubusercontent.com/28022134/44613352-2bcd3780-a7c7-11e8-8a47-b6a5c1f4b769.gif)
Above is a gif demonstrating the issue I am talking about. below is the code used to achieve these results.
```
<action-landmark>
    <div class="range-slider">
        <input class="input-range" type="range" step="1" value={ appConfig.pointSize || 4} min="3" max="100" onchange={changeScale}>
    </div>
    <script>

        this.changeScale = function(e){
            appConfig.pointSize = e.target.value;
           $(".labelpoint").attr("r", e.target.value);
        }

    </script>
</action-landmark>
```

**Comment by amitguptagwl** [comment]
@jaknowles97 The radius is hard coded on https://github.com/NaturalIntelligence/imglab/blob/master/js/config.js#L126 . You'll have to change the code to take the value from **appConfig.featurePointSize**

**Comment by jaknowles97** [comment]
@amitguptagwl I got it to work but I am not understanding the appConfig.featurePointSize part of it. I just declared a global variable named "featurePointSize" in config.js, then in the action-landmark I set featurePointSize = e.target.value;

**Comment by amitguptagwl** [comment]
If all the global configuration variable are the part of appconfig then the configuration can be saved so that user need not to it always. In this way, we need not to create many global variables
