### ISSUE TITLE
Tracking lines on big image file are not being displayed correctly

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#7]
Steps to reproduce

1. Loan an image which is bigger than canvas size.
2. You must see the scroll bar in canvas
3. now scroll and move the cursor. You'll not see the tracking line

![screenshot from 2018-04-26 05-58-38](https://user-images.githubusercontent.com/7692328/39279477-077fbf92-4917-11e8-8fe9-9421ab505443.png)

Possible solution

1. Set the height & width when image is loaded as per imgoverlay not container.

**Comment by programmer-pixie** [comment]
Hello, if this issue is still available, may I try to fix it?

**Comment by amitguptagwl** [comment]
Yes, please go on. Please mention issue number in the PR.

**Comment by amitguptagwl** [comment]
As there is no response from the claimer @programmer-pixie , this issue is free to be picked by other contributors.

**Comment by amitguptagwl** [comment]
Will be covered in UI renovation
