### ISSUE TITLE
create bootstrap tabs

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#70]
1. pen the following link : https://naturalintelligence.github.io/imglab/
2. Click on menu icon > settings

Settings modal window should have 2 tabs: General, and Data.

Current data should be shown under General tab.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by lopyos** [comment]
<settings-window>
    <style>
        #settings-wrapper{
            min-height: 500px;
            /* min-width: 400px; */
        }
    </style>
    <div id="settings-wrapper">
    	<div id="row">
    		<div class="col-xs-4">
    			<h3>Auto Save</h3>
    		</div>
    		<div class="col-xs-4">
    			<button class="btn btn-theme">General</button>
    		</div>
    		<div class="col-xs-4">
    			<button class="btn btn-theme">Data</button>
    		</div>
    	</div>        
        <small>We auto save labeling data in browser cache.</small>
        <br>
        <div class="row">
            <div class="col-6"> 
                Syncing Interval 
                <small><i class="icon-attention-circled small" data-toggle="tooltip" title="Change how early the data should be saved in browser cache.  Set 0 to disable. Minimum value is 4 sec."></i></small>
            </div>
            <div class="col-6 float-right">
                <input  type="text" value={ appConfig.autosave.syncingInterval / 1000} size=4 onchange={changeInterval}> <small></small> seconds
            </div>
        </div>
        
        <br>
        <div>
            <button class="btn btn-theme" onclick={clearCache}>Clear cache</button>
        </div>
    </div>
    <script>
        this.changeInterval = function(e){
            if(e.target.value === 0){
                appConfig.autosave.enable = false;
            }else if(e.target.value < 4) {
                appConfig.autosave.enable = true;
                appConfig.autosave.syncingInterval = 4 * 1000;
                this.update();
            }else{
                appConfig.autosave.enable = true;
                appConfig.autosave.syncingInterval = e.target.value * 1000;
            }
        }

        
    </script>
</settings-window>

**Comment by lopyos** [comment]
<div id="settings-wrapper">
    	<div id="row">
    		<div class="col-xs-4">
    			<h3>Auto Save</h3>
    		</div>
    		<div class="col-xs-4">
    			<button class="btn btn-theme">General</button>
    		</div>
    		<div class="col-xs-4">
    			<button class="btn btn-theme">Data</button>
    		</div>
    	</div>        
        <small>We auto save labeling data in browser cache.</small>
        <br>
        <div class="row">
            <div class="col-6"> 
                Syncing Interval 
                <small><i class="icon-attention-circled small" data-toggle="tooltip" title="Change how early the data should be saved in browser cache.  Set 0 to disable. Minimum value is 4 sec."></i></small>
            </div>
            <div class="col-6 float-right">
                <input  type="text" value={ appConfig.autosave.syncingInterval / 1000} size=4 onchange={changeInterval}> <small></small> seconds
            </div>
        </div>

**Comment by amitguptagwl** [comment]
Though it'll be helpful. But your effort should be counted. Create on fork button on top right. Do the changes, test it and then raise a PR.

**Comment by amitguptagwl** [comment]
@lopyos It looks like that your changes have added the tabs but when we press data tab, a blank page was expected.

**Comment by lopyos** [comment]
@amitguptagwl  for that is needed to add some jquery to hide the information that is displayed in general...and on click !!! show the information that we want.

I'm kind of asking because is my first contribution and I don't know how do you prefer the things to be done .. do you want me to use jquery?

**Comment by Alvin-Voo** [comment]
Hi @amitguptagwl. Is this what you are looking for? =)

![imglab_ 70](https://user-images.githubusercontent.com/28261161/44185764-12354b80-a148-11e8-8ddd-2345605b6c09.gif)

**Comment by amitguptagwl** [comment]
Yes for the starting. Later we'll add some options to Data tab.

**Comment by Alvin-Voo** [comment]
@amitguptagwl Alright, I have created a PR for this. Please review. Thanks!
