### ISSUE TITLE
Why face++ doesn't work?

### ISSUE THREAD

**Issue by HymEric** [NaturalIntelligence/imglab#71]
When I registered  to use face++ to use the API yesterday, it seemly doesn't work in https://naturalintelligence.github.io/imglab/. So I want to get some suggestions. Thank you!

**Comment by amitguptagwl** [comment]
If you're using Face++ first time then it's probably at face++ side. Check #2 issue for more detail.

You'll have to report their customer care.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by HymEric** [comment]
Thank you. But face++ reply me they don't know this web imgLab tool.

**Comment by amitguptagwl** [comment]
You must not mention imglab. They don't have any relation with this tool.

You just check browser console for the error or hit their curl command to check if it is working fine and report them if any error.

Otherwise tomorrow I'll check with my cred and will update you tomorrow

**Comment by HymEric** [comment]
OK. But I can't find "console" after after it said "Error in connecting face++ API. Check console for more deetail". I'm looking forward to your checking.

**Comment by amitguptagwl** [comment]
Are you getting this error you mentioned? If yes then this is the issue at face++ side. However I'll you tomorrow to find the issue. Today I'm busy in an issue

**Comment by amitguptagwl** [comment]
@HymEric I've confirmed that the Imglab application is not broken and working fine.

To report them you can either run below curl command with your detail.

```
curl -X POST "https://api-us.faceplusplus.com/facepp/v3/detect" -F "api_key=YOUR_KEY" \
-F "api_secret=YOUR_SECRET" \
-F "image_file=FILENAME" \
-F "return_landmark=1" \
-F "return_attributes=gender,age"
```

Or open imglab, open console (press F12 key for that), and use your credential to use face++ API. Check the errors on console and copy paste here.

**Comment by HymEric** [comment]
The error of console is:
Failed to load resource: the server responded with a status of 401 ()
/imglab/#:1 Failed to load https://api-us.faceplusplus.com/facepp/v3/detect: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://naturalintelligence.github.io' is therefore not allowed access. The response had HTTP status code 401.
tags/plugins/facepp.tag.html.js:52 Error in connecting face++ API Object
error @ tags/plugins/facepp.tag.html.js:52

If you have time, please help me.

**Comment by amitguptagwl** [comment]
Are you using the correct api_key and api_secret ?

**Comment by HymEric** [comment]
Yes, I used.  But it is the free api_key and secret.

**Comment by amitguptagwl** [comment]
Yes it is fine. Drop them an email stating that when you're using Face++ API, you're getting following error

"Failed to load https://api-us.faceplusplus.com/facepp/v3/detect: No 'Access-Control-Allow-Origin' header is present on the requested resource." The response had HTTP status code 401. However, when my friend is using his credentials then it is working fine.


Let me know what do they response.

**Comment by amitguptagwl** [comment]
This problem is related to CORS. They manually enable it I guess

https://social.msdn.microsoft.com/Forums/en-US/bd430bd6-06fb-4bb3-9dfd-5d395c5dc6f5/face-api-javascript-api-no-accesscontrolalloworigin-header-error?forum=mlapi
