### ISSUE TITLE
Firefox browser support

### ISSUE THREAD

**Issue by rclim-11** [NaturalIntelligence/imglab#73]
****
ImgLab doesn't work in Modzilla Firefox

**To Reproduce**
1. Open ImgLab in Firefox
2. Attempt to open image files

**Console Errors**
> Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-119603824-1”. imglab:24
> TypeError: input is undefined[Learn More] imglab:52:1

**Device detail:**
 - OS: Windows 10
 - Browser Firefox Quantum 61.0.1 (64-bit)

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
I'm really addicted to chrome. I can't find the tags folder in console>source in firefox. Marking it as bug but not able to debug.
