### ISSUE TITLE
Delete animation

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#76]
Tell us what feature you're looking for and how it can help you and others in general.

When a feature point is deleted from right panel, we want to give it some animation.
![screenshot from 2018-07-28 06-59-04](https://user-images.githubusercontent.com/7692328/43351716-c3311078-9233-11e8-923a-27a086cdc838.png)

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
@Alvin-Voo Thanks for your and time. Yes this is what I meant animation wise. But I'm expecting the changes in [label-panel.tag.htm](https://github.com/NaturalIntelligence/imglab/blob/master/tags/label-panel.tag.html). You can define the CSS in style section and can take necessary action in `tag.deleteTag()`.

**Comment by Alvin-Voo** [comment]
Hi @amitguptagwl . Yes, I made the changes in label-panel.tag.htm. Previously I tried using the jquery functions in tag.deleteTag() but its not really working properly. After jquery has changed the DOM li objects (by appending CSS classes), riotjs cannot update the `<li>` list properly. I am referring to below 2 lines:

```
<p class="mb-2">Feature Points  <small>{ this.targetShape.featurePoints.length }</small></p>
...
<li class="li-fpoints grey-border" each={fPoint,fid in targetShape.featurePoints}>
```
targetShape.featurePoints would be wrong. Those `<li>` that has been 'animated' somehow are still around even though they should have been removed. I suspect we cannot use jquery which followed by a need to immediately update the DOM again by riotjs. Hence, I propose to define the click function using jquery itself inside the tag.on("mount",...) of label-panel.tag.htm. The below works.

```
            $(".input-group-btn").click(function(e){
                let fid = $(this).attr("id");
                let optsid = tag.opts.id;
                $("#li-fpoints-"+fid)
                .addClass('animated slideOutRight')
                .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){
                  console.log("after animation");
                  detachPointByIndex(optsid, fid);
                  tag.update();
                  riot.mount('workarea',{ img : imgSelected});
                });
            })
```

**Comment by amitguptagwl** [comment]
You need not to use jquery to attach the click event.

```js
        tag.deleteTag = function(e){
            detachPointByIndex(opts.id, e.item.fid);
            this.update();
            riot.mount('workarea',{ img : imgSelected});
        }
```

You can use `$(e.target) in above code

**Comment by amitguptagwl** [comment]
@Alvin-Voo let me know if you're stuck

**Comment by Alvin-Voo** [comment]
Hi @amitguptagwl 

Yes. As I mentioned, I did try to add directly inside the tag.deleteTag function but it didnt work, with the code below.

```
        tag.deleteTag = async function(e){
            let fid = e.item.fid;
            let optsid = opts.id;
            await $("#li-fpoints-"+fid).addClass('animated slideOutRight')
            .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend');
            console.log("after animation");
            detachPointByIndex(optsid, fid);
            this.update();
            riot.mount('workarea',{ img : imgSelected});
}
```
This is the result. Those `<li>` that has been appended the 'animated' CSS class cannot be updated correctly by riotjs.
![peek 2018-08-15 09-47](https://user-images.githubusercontent.com/28261161/44127534-4f9926f0-a070-11e8-98f3-dd6493df5b2e.gif)

In ANY CASE, the $(e.target) you mentioned refers to `<i class="icon icon-trash-empty"></i>`. We wan to animate the `<li>` object instead of the trash can. =)

I guess any code that changes the DOM should be added inside the tag.mount

**Comment by amitguptagwl** [comment]
Can't we use `$(e.target).parent('li')`?

> I guess any code that changes the DOM should be added inside the tag.mount

No it's not necessary.

I hope this should work (just modified your code, not tested)

```js
tag.deleteTag = function(e){
    $(e.target).parent('li')
        .addClass('animated slideOutRight')
        .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){
            detachPointByIndex(opts.id, e.item.fid);
            tag.update();
            riot.mount('workarea',{ img : imgSelected});
        });
}
```

**Comment by Alvin-Voo** [comment]
Ok @amitguptagwl  it works! But with a little modification since .parent() only traverse one level up

```
        tag.deleteTag = function(e){
          $(e.target).parent().parent().parent('li')
            .addClass('animated slideOutRight')
            .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){
                detachPointByIndex(opts.id, e.item.fid);
                tag.update();
                riot.mount('workarea',{ img : imgSelected});
            });
        }
```

![peek 2018-08-15 10-40](https://user-images.githubusercontent.com/28261161/44128897-08ad76e4-a078-11e8-91c1-3022e63ae9eb.gif)

Let me know if I could create the PR. Thanks.

**Comment by Alvin-Voo** [comment]
Ok, instead of that ugly syntax, I think we could use .parents()

```
        tag.deleteTag = function(e){
          $(e.target).parents('li')
            .addClass('animated slideOutRight')
            .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){
                detachPointByIndex(opts.id, e.item.fid);
                tag.update();
                riot.mount('workarea',{ img : imgSelected});
            });
        }
```

**Comment by amitguptagwl** [comment]
Yes I meant that. Sorry for typo. Please go ahead with PR

**Comment by Alvin-Voo** [comment]
Hi @amitguptagwl . Done. Please review =)

**Comment by amitguptagwl** [comment]
Done. I'll update the contributors list on README soon. or you can add your name in last.
