### ISSUE TITLE
Import data file

### ISSUE THREAD

**Issue by Onotoko** [NaturalIntelligence/imglab#78]
Hi friend,
Thank you for the great application and do not know what is the feature import data file? what if It contains the annotations of image? If it true, what is the format?
Thanks!

**Comment by amitguptagwl** [comment]
When you work with imglab, you can export data in multiple formats : COCO, Pascal VOC, dlib pts, dlib xml, nimn. ( some more will be supported in future)

It is quite difficult to annotate all the images in one go. You may want to save annotation data so you can continue later. Imglab by default save data in browser. However you can save the project file which can be imported later to resume your work. Project file is saved in [Nimn data format](http://nimn.in). Imglab project file contains maximum detail of annotation which can be lost with other formats. So it is always recommended to export project file for future work.

In addition, if you export data in dlib xml format, you can import that as well. It is helpful when you already have annotation data in dlib xml format and want to continue annotation in imglab.

Importing from other formats will be supported in future

> Please [bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) this project
