### ISSUE TITLE
Refactoring: move dlib.js to dataformaters

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#85]
> This issue is suitable and prioritized to first-timers. But can be picked by other contributors if not handled within initial 4 weeks.

Move js/dlib.js to dataformaters folder. Don't forget to change the reference in index.html. And test the application if nothing is broken.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by coderquill** [comment]
Hey @amitguptagwl , I would like to work on this issue. I just have to move dlib.js from js to dataformaters folder and change its reference in index.html from "js/dlib.js" to "dataformaters/dlib.js",right?

**Comment by amitguptagwl** [comment]
Yes. But also run the application to check there is not any error in console

**Comment by coderquill** [comment]
Okay, will do it . Thanks!

**Comment by coderquill** [comment]
Hey @amitguptagwl , I have raised the PR, can you please review it?

**Comment by amitguptagwl** [comment]
This issue is free to be picked any new contributor.

**Comment by gowrimanoharir** [comment]
Hi @amitguptagwl I would like to pick this up.

**Comment by amitguptagwl** [comment]
Yes please go on.

**Comment by gowrimanoharir** [comment]
@amitguptagwl  Thank you, created the PR. Also tested in Chrome, Firefox and Edge did not see any console errors except for below which exists in Master as well (before the move).

Loading failed for the <script> with source http://127.0.0.1:8080/js/thirdparty/svg-pan-zoom.min.js

**Comment by amitguptagwl** [comment]
"svg-pan-zoom.min.js" lib must have been removed. Can you please check and remove if it is being referred from the code?

**Comment by gowrimanoharir** [comment]
@amitguptagwl Fixed the svg min zoom console error and tested to make sure it is not thrown anymore.
