### ISSUE TITLE
Discontinue with v1

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#88]
As maximum users have been moved to v2 of imglab, we have to delete the code being used by only v1 with a warning message on README in advance.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by amitguptagwl** [comment]
@derekdkim your previous issue is not fixed yet. Check my comments on PR, please.

**Comment by derekdkim** [comment]
I deleted the files that were only being used by old.html and updated the readme to reflect that we've deleted the legacy version. I'm currently working on deleting some references in CSS that are reference elements or classes that only exist in old.html.

I don't have much experience with bootstrap or jQuery, so I will just leave it the same way.

I'm testing the index.html to make sure I don't disturb anything with every change, so this might take a little while.

**Comment by derekdkim** [comment]
I'm not sure what the reason could be but as I was testing index.html (new version) on different browsers, I noticed that the left-hand toolbar is missing. This is only a problem in Chrome and IE, but Firefox and MS Edge are unaffected. So I reverted back to the commit where I only updated the readme, and it still didn't work. Do you know what the reason for this could be?

**Comment by alextychan** [comment]
@derekdkim, please open a pull request and we'll work from there. 

As for searching for dead javascript code, I would suggest looking at removing whatever's not in the current index.html as those should not be needed. E.g. any scripts that aren't imported in the current index.html but were used in the old one.

**Comment by amitguptagwl** [comment]
@derekdkim were you testing by running index.html directly in the browser or by running it on a server?

**Comment by derekdkim** [comment]
I was testing it by running index.html directly in the browser but @alextychan suggested a workaround in the PR. It works perfectly with the live-server.
