### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#93]
> This issue is suitable and prioritized to first-timers. But can be picked by other contributors if not handled within initial 4 weeks.

To decrease the loading time, we should minify js, and css files. `fontello.css` is one of them which is less frequently get changed.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by williamrhp** [comment]
Hello Amit. I am a new developer who just completed a bootcamp program. I am looking for some open source projects to contribute to and I saw you have many issues labeled "first-timers". Would this be an appropriate project for me to work on? I have never contributed before, so please excuse me if I might take a while to pick up on how things work in terms of contributions. Thank you.

**Comment by amitguptagwl** [comment]
@williamrhp Yes you're on the right project. Though there are some issues which are tagged as first timers but now they have been matured. But you'll definitely find some issues which can be easily done like this one. So go ahead. I'll try to guide you wherever you stuck.

**Comment by amitguptagwl** [comment]
@williamrhp Try this one https://github.com/NaturalIntelligence/imglab/pull/90

**Comment by amitguptagwl** [comment]
This issue is released to be picked by any other contributor.

**Comment by Acemad** [comment]
Hello, if nobody is working on this, can I do it ? Thank you .

**Comment by amitguptagwl** [comment]
Sure. Try it.

**Comment by Acemad** [comment]
Pull Request #120 created, please review. Thank you.

**Comment by davelip** [comment]
Is there a task automation script to replicate this?

**Comment by amitguptagwl** [comment]
not yet. But there should be.
