### ISSUE TITLE
Change the color of landmark/feature point

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#94]
Same as #65 , we want to provide an option in action bar to let user decide the color of feature point. Currently it is red always.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

**Comment by sumit9696** [comment]
can i work on this issue?

**Comment by amitguptagwl** [comment]
Yes please. Please let me know what is your plan before raising PR so we can verify our understanding.

**Comment by sumit9696** [comment]
I am new to open source contributions. So, it would be helpful if you can guide me.

**Comment by sumit9696** [comment]
Do i need to make changes in tags\actions folder?

**Comment by amitguptagwl** [comment]
Yes

**Comment by amitguptagwl** [comment]
@sumit9696 any update?

**Comment by alextychan** [comment]
Hi, I am new to contributing and would like to take over this issue. I've already implemented the feature using an external color picker called Spectrum. Once a color is picked, it is saved into a global variable via appConfig. It is still limited in the sense that changing the color for one point would change all the colors. 

Please have a look. 
![screenshot_2018-09-13 imglab - image annotation tool](https://user-images.githubusercontent.com/17516052/45520922-aca99e80-b789-11e8-82d1-3878628bfef9.png)
![screenshot_2018-09-13 imglab - image annotation tool 1](https://user-images.githubusercontent.com/17516052/45520926-b16e5280-b789-11e8-938c-eaa51152fa48.png)

**Comment by amitguptagwl** [comment]
Thanks for the changes @alextychan . I liked the way to represent your understanding. PR has been merged now.
