### ISSUE TITLE
Uncaught TypeError: Cannot read property 'class' of undefined

### ISSUE THREAD

**Issue by forconz** [NaturalIntelligence/imglab#99]
**Describe the bug**
I git clone the source code from https://github.com/NaturalIntelligence/imglab.git
I copy the source code to server, and use a domain to browse index.html
I can not see anything but Img Lab text, logo and donate button.
I press F12, and I get some errors

**To Reproduce**
1.  git clone https://github.com/NaturalIntelligence/imglab.git
2.  copy source code to server, create site from iis and bind a domain
3.  browse the domain ,
4.  press F12 to see browser console logs
5.  see errors

**Screenshots**
![20180908121148](https://user-images.githubusercontent.com/9990289/45250178-6ce55000-b360-11e8-9a97-96e4dd32fe82.png)

**Console Errors**
Failed to load resource: the server responded with a status of 404 (Not Found)
riot.min.js:2 Uncaught TypeError: Cannot read property 'class' of undefined
    at ye (riot.min.js:2)
    at t (riot.min.js:2)
    at gt (riot.min.js:2)
    at t (riot.min.js:2)
    at Object.Qt [as mount] (riot.min.js:2)
    at (index):145

**Comment by amitguptagwl** [comment]
Don't access index.html in the browser directly. Instead, use some server to serve the contents : https://www.npmjs.com/package/http-server

**Comment by amitguptagwl** [comment]
Do you mean you're not able to export data file when you use polygon shape to label an image? which data format you're exporting to?
